version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sistema_restaurantes_db
    environment:
      POSTGRES_DB: sistema_restaurantes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - restaurantes-network

volumes:
  postgres_data:

networks:
  restaurantes-network:
    driver: bridge